apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  releaseName: metallb
  targetNamespace: metallb
  storageNamespace: metallb
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb
  values:
  install:
    createNamespace: true
    disableWait: true
  upgrade:
    disableWait: true
  interval: 7m0s
